name: Hello World
on: [push]

jobs:
  Hello-World-Job:
    # your CodeBuild-hosted runner label
    runs-on:
      - codebuild-Demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4

      # Your original step(s)
      - run: echo "Hello I am from GitHub ghfhgfAction workflow!"
