name: Hello World
on: [push]

jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-Demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug AWS Environment
        if: ${{ always() }}
        run: |
          set -x
          echo "=== AWS Environment Debug ==="
          echo "Testing AWS CLI access..."
          aws sts get-caller-identity || echo "AWS CLI failed: $?"
          
          echo "Current AWS region:"
          aws configure get region || echo "No default region set"
          
          echo "Environment variables:"
          env | grep -E "(AWS|CODEBUILD)" || echo "No AWS/CodeBuild vars found"

      - name: Emit runner->CB binding
        if: ${{ always() }}
        run: |
          set -x
          echo "=== GitHub Variables ==="
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_WORKFLOW=$GITHUB_WORKFLOW"
          echo "CODEBUILD_BUILD_ID=${CODEBUILD_BUILD_ID:-unknown}"
          echo "RUNNER_LABELS=${RUNNER_LABELS:-unknown}"

          echo "=== Testing CloudWatch Logs ==="
          # Test log group creation
          echo "Creating log group..."
          aws logs create-log-group --log-group-name "/gha-runner/bindings" 2>&1 || echo "Log group creation failed: $?"
          
          # Test log stream creation
          echo "Creating log stream..."
          aws logs create-log-stream --log-group-name "/gha-runner/bindings" --log-stream-name "default" 2>&1 || echo "Stream creation failed: $?"
          
          # Test putting a simple log event
          echo "Testing log event..."
          TS=$(date +%s%3N)
          MSG='{"test":"debug","run_id":"'$GITHUB_RUN_ID'"}'
          aws logs put-log-events --log-group-name "/gha-runner/bindings" --log-stream-name "default" --log-events timestamp=$TS,message="$MSG" 2>&1 || echo "Log event failed: $?"
          
          echo "=== Debug completed ==="





