name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-Runner-Project-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
      - image:codebuilrepo:latestt
    steps:
      - run: echo "Hello World!"
